### ISSUE TITLE
Get Latest League Version

### ISSUE THREAD

**Issue by eddy5641** [szungy/LeagueSpectate#1]
You can use this to get the latest ddragon version, which usually is the latest league of legends version
public string GetDragon()
        {
            string dragonJSON = "";
            using (WebClient client = new WebClient())
            {
                dragonJSON = client.DownloadString("http://ddragon.leagueoflegends.com/realms/na.js");
            }
            dragonJSON = dragonJSON.Replace("Riot.DDragon.m=", "").Replace(";", "");
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            Dictionary<string, object> deserializedJSON = serializer.Deserialize<Dictionary<string, object>>(dragonJSON);
            string Version = (string)deserializedJSON["v"];
            string CDN = (string)deserializedJSON["cdn"];
            string s = CDN + "/dragontail-" + Version + ".tgz";
            return Version;
        }

**Comment by szungy** [comment]
Thanks for the recommendation but the DDragon data is inaccurate and therefore it is not good for the login process (even a slight digit mismatch causes the process to fail) but i'll try to find a way to dynamically get the league version.
